# Generated by Django 3.2.11 on 2022-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='log',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
