# Generated by Django 3.2.11 on 2022-01-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stuffs',
            new_name='gpu',
        ),
    ]
