# Generated by Django 4.0.1 on 2022-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0003_auto_20220110_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='new',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='etc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='power',
            name='is24pin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='new',
            field=models.BooleanField(null=True),
        ),
    ]
