# Generated by Django 3.2.11 on 2022-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_card_ram_size', models.SmallIntegerField()),
                ('series', models.CharField(max_length=10)),
                ('computer_memory_type', models.CharField(max_length=10)),
                ('new_or_stock', models.NullBooleanField()),
                ('issue', models.CharField(max_length=100)),
                ('countX', models.SmallIntegerField()),
                ('etc', models.CharField(max_length=100)),
            ],
        ),
    ]
