# Generated by Django 3.2.11 on 2022-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_rename_stuffs_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watt', models.SmallIntegerField()),
                ('is24pin', models.NullBooleanField()),
                ('new', models.NullBooleanField()),
                ('issue', models.CharField(max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='countX',
            new_name='countt',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='new_or_stock',
            new_name='new',
        ),
    ]
