# Generated by Django 3.2.11 on 2022-01-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0004_alter_gpu_new_alter_power_etc_alter_power_is24pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10)),
                ('new', models.BooleanField(null=True)),
                ('issue', models.CharField(max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='xxxx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_card_ram_size', models.SmallIntegerField()),
                ('series', models.CharField(max_length=10)),
                ('computer_memory_type', models.CharField(max_length=10)),
                ('new', models.BooleanField(null=True)),
                ('issue', models.CharField(max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(max_length=100)),
            ],
        ),
    ]
