# Generated by Django 3.2.11 on 2022-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0006_auto_20220113_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='series',
            field=models.CharField(max_length=100),
        ),
    ]
