# Generated by Django 3.2.11 on 2022-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0007_alter_cpu_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.SmallIntegerField()),
                ('hardtpype', models.CharField(blank=True, max_length=100)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='keybordandmouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keybordormouse', models.CharField(max_length=100)),
                ('vgaorusb', models.CharField(blank=True, max_length=100)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MOTHERBOARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramtype', models.CharField(max_length=100)),
                ('ramsize', models.SmallIntegerField()),
                ('new', models.BooleanField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('countt', models.SmallIntegerField()),
                ('etc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cpu',
            name='issue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='new',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='etc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='issue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='new',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='is24pin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='issue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='power',
            name='new',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='watt',
            field=models.CharField(max_length=100),
        ),
    ]
