# Generated by Django 4.0.1 on 2022-01-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0008_auto_20220113_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='log',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
